    <button type="button" title="<?php echo $this->__('Back') ?>" class="button" onClick='location.href="<?php echo $this->getUrl("adminhtml/visitors/index") ?>"'>
        <span>
            <span>
                <?php echo $this->__('Back') ?>
            </span>
        </span>
    </button>


<button type="button" title="<?php echo $this->__('< Previous ID') ?>" class="button" onClick='location.href="<?php echo $this->getUrl('*/*/view', array('visit_id' => $this->navigation['prevId'])) ?>"'>
    <span>
        <span>
            <?php echo $this->__('< Previous ID') ?>
        </span>
    </span>
</button>

<button type="button" title="<?php echo $this->__('Next ID >') ?>" class="button" onClick='location.href="<?php echo $this->getUrl('*/*/view', array('visit_id' => $this->navigation['nextId'] )) ?>"'>
    <span>
        <span>
            <?php echo $this->__('Next ID >') ?>
        </span>
    </span>
</button>


<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__("Информация о посетителе!") ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <table cellspacing="25" width="100%">
        <tr>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('ID Посетителя') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getId();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Дата посещения') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getVisitDate();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Время посещения') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getVisitTime();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Время проведенное на сайте') ?></h4></div>
                    <fieldset class="np"><?php echo $this->timeOnSite;?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('ОС') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getSysString();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Полное название ОС') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getSysFullname();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Название браузера') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getBrowserName();?></fieldset>
                </div>
            </td>

            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Версия браузера') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticVisits']->getBrowserVersion();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Континент') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticCountry']->getContinent();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Страна') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticCountry']->getCountryNameEn();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Город') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticCountry']->getCityNameEn();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('IP пользователя') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticIpAddresses']->getIp();?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('IP сервера') ?></h4></div>
                    <fieldset class="np"><?php echo $this->visitorInformation['statisticIpAddresses']->getIpServer();?></fieldset>
                </div>

            </td>

            <td>
                <div class="entry-edit" style="border:1px solid #ccc;">
                    <div style="margin:20px;">
                        <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
                        <div style='overflow:hidden;height:440px;width:700px;'>
                            <div id='gmap_canvas' style='height:440px;width:700px;'></div>
                            <div><small><a href="http://embedgooglemaps.com">embedgooglemaps.com</a></small></div>
                            <div><small><a href="http://www.genkigirl.net/">cheap website traffic</a></small></div>
                            <style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
                        </div>
                        <script type='text/javascript'>
                            function init_map(){
                                var myOptions = {
                                    zoom:10,
                                    center:new google.maps.LatLng(<?php echo $this->visitorInformation['statisticCountry']->getLat();?>,<?php echo $this->visitorInformation['statisticCountry']->getLon();?>), /*Вставить координаты из базы*/
                                    mapTypeId: google.maps.MapTypeId.ROADMAP
                                };
                                map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);
                                marker = new google.maps.Marker({
                                    map: map,
                                    position: new google.maps.LatLng(<?php echo $this->visitorInformation['statisticCountry']->getLat();?>,<?php echo $this->visitorInformation['statisticCountry']->getLon();?>) /*Вставить координаты из базы*/
                                });
                                infowindow = new google.maps.InfoWindow({
                                    content:'<strong>Название</strong><br><?php echo $this->visitorInformation['statisticCountry']->getCityNameEn();?>, <?php echo $this->visitorInformation['statisticCountry']->getCountryNameEn();?><br>' /*Вставить город и страну из базы*/
                                });
                                google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});
                                infowindow.open(map,marker);
                            }
                            google.maps.event.addDomListener(window, 'load', init_map);
                        </script>
                    </div>
                </div>
            </td>
        </tr>
    </table>
</div>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__("Карта переходов") ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <table width="100%">

        <tr>
            <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('№') ?></h4></div>
            </div>
            </td>
            <td>
                <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Referrer') ?></h4></div>
                </div>
            </td>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Ссылка') ?></h4></div>
                </div>
            </td>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Заголовок страницы') ?></h4></div>
                </div>
            </td>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Дата') ?></h4></div>
                </div>
            </td>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Время посещения') ?></h4></div>
                </div>
            </td>
            <td>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Время на странице') ?></h4></div>
                </div>
            </td>
        </tr>

        <?php $t =''; foreach ($this->dataVisitors as $key=>$value):?>
            <tr>
                <td>
                    <div class="entry-edit">
                        <?php echo $key;?>
                    </div>
                </td>
                <td>
                    <div class="entry-edit">
                        <a href="<?php echo $value['referrer']?>"><?php echo mb_strimwidth($value['referrer'],0,40,"...")?></a>
                    </div>
                </td>
                <td>
                    <div class="entry-edit">
                        <a href="<?php echo $value['page']?>"><?php echo mb_strimwidth($value['page'],0,40,"...")?></a>
                    </div>
                </td>
                <td>
                    <div class="entry-edit">
                        <?php echo $value['page_title']?>
                    </div>
                </td>
                <td>
                    <div class="entry-edit">
                        <?php echo $value['visit_date']?>
                    </div>
                </td>
                <td>
                    <div class="entry-edit">
                        <?php echo $value['visit_time']?>
                    </div>
                </td>
                <td>
                    <div class="entry-edit">
                        <?php
                            $time1 = date_create($value['visit_time']);
                            $time2 = date_create($this->dataVisitors[$key+1]['visit_time']);
                            $interval = date_diff($time2, $time1);
                            if(!$this->dataVisitors[$key+1]==null){
                                $interval = date_diff($time2, $time1);
                                $t =$t +strtotime($interval->format('%H:%I:%S'));
                                echo $interval->format('%H:%I:%S');
                            }else {
                                echo "Пользователь покинул сайт";
                                break;
                            }
                        ?>
                    </div>
                </td>
            </tr>
        <?php endforeach;
        ?>
    </table>

</div>
