
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Статистика посещения сайта!') ?></h3></td>
        </tr>
    </table>
</div>

<div class="dashboard-container">

    <table cellspacing="25" width="100%">
        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Всего') ?></h4></div>
                <fieldset class="np"><?php echo Mage::registry('allvisits');?></fieldset>
            </div>
        </td>

        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Год') ?></h4></div>
                <fieldset class="np"><?php echo Mage::registry('year');?></fieldset>
            </div>
        </td>

        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Месяц') ?></h4></div>
                <fieldset class="np"><?php echo Mage::registry('month');?></fieldset>
            </div>
        </td>

        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('День') ?></h4></div>
                <fieldset class="np"><?php echo Mage::registry('day');?></fieldset>
            </div>
        </td>

        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Час') ?></h4></div>
                <fieldset class="np"><?php echo Mage::registry('hour');?></fieldset>
            </div>
        </td>

        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Минута') ?></h4></div>
                <fieldset class="np"><?php echo Mage::registry('minute');?></fieldset>
            </div>
        </td>

        <td>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $this->__('Пириуд') ?></h4></div>
                    <fieldset class="np">
                        <form class="my-form" name="myForm" id="myForm" method="post" >
                            <div class="input-box">
                                From: <input class="required-entry" type="text" name="from_data" id="_from">
                                <img title="Select date" id="_from_trig" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>" class="v-middle">
                                To: <input class="required-entry" type="text" name="to_data" id="_to">
                                <img title="Select date" id="_to_trig" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>" class="v-middle">
                            </div>

                            <script type="text/javascript">
                                Calendar.setup({
                                    inputField : '_from',
                                    ifFormat : '%Y-%m-%d',
                                    button : '_from_trig',
                                    align : 'Bl',
                                    singleClick : true
                                });
                                Calendar.setup({
                                    inputField : '_to',
                                    ifFormat : '%Y-%m-%d',
                                    button : '_to_trig',
                                    align : 'Bl',
                                    singleClick : true
                                });
                            </script>
                            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_key"/>
                            <button id="enter">Enter</button>
                        </form>
                        <?php echo Mage::registry('period');?>
                    </fieldset>
                </div>
            </div>
        </td>
    </table>
</div>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Графики') ?></h3></td>
        </tr>
    </table>
</div>


<h3>% браузеров посетителей</h3>
<div class="dashboard-container" style="border:1px solid #ccc; width:550px;height:550px;padding:5px">
    <canvas id="myBrowser" width="400" height="400"></canvas>
    <script>
        var my_chart_canvas = document.getElementById("myBrowser");
        var my_chart = new Chart(my_chart_canvas, {
            type: 'doughnut',
            data: {
                datasets: [
                    {
                        data: [<?php echo Mage::registry('data')?>],
                        backgroundColor: [<?php echo Mage::registry('rgba');?>]
                    }
                ],
                labels: [<?php echo Mage::registry('legend_browser');?>]
            },
            options: {
                layout: {
                    padding: {
                        left: 10,
                        right: 10,
                        top: 10,
                        bottom: 10
                    }
                },
                legend: {
                    display: true,

                },
                title: {
                    display: true,
                    text: '% браузеров посетителей',
                    fontSize: 15,
                }
            }

        });
    </script>
</div>

<div class="dashboard-container" style="border:1px solid #ccc; width:550px;height:550px;padding:5px">
    <canvas id="myOS" width="400" height="400"></canvas>
    <script>
        var my_chart_canvas = document.getElementById("myOS");
        var my_chart = new Chart(my_chart_canvas, {
            type: 'doughnut',
            data: {
                datasets: [
                    {
                        data: [<?php echo Mage::registry('data_os');?>],
                        backgroundColor: [<?php echo Mage::registry('rgba_os');?>]
                    }
                ],
                labels: [<?php echo Mage::registry('legend_os');?>]
            },
            options: {
                layout: {
                    padding: {
                        left: 10,
                        right: 10,
                        top: 10,
                        bottom: 10
                    }
                },
                legend: {
                    display: true,

                },
                title: {
                    display: true,
                    text: '% ОС посетителей',
                    fontSize: 15,
                }
            }
        });
    </script>
    </div>

<div class="dashboard-container" style="border:1px solid #ccc; width:550px;height:550px;padding:5px">
    <canvas id="myContonents" width="400" height="400"></canvas>
    <script>
        var my_chart_canvas = document.getElementById("myContonents");
        var my_chart = new Chart(my_chart_canvas, {
            type: 'doughnut',
            data: {
                datasets: [
                    {
                        data: [<?php echo Mage::registry('continent_data');?>],
                        backgroundColor: [<?php echo Mage::registry('continent_rgba');?>]
                    }
                ],
                labels: [<?php echo Mage::registry('continent_legend');?>]
            },
            options: {
                layout: {
                    padding: {
                        left: 10,
                        right: 10,
                        top: 10,
                        bottom: 10
                    }
                },
                legend: {
                    display: true,

                },
                title: {
                    display: true,
                    text: '% континентов посетителей',
                    fontSize: 15,
                }
            }
        });
    </script>
</div>

<!-- Карта гугл -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    google.charts.load('current', { 'packages': ['map'] });
    google.charts.setOnLoadCallback(drawMap);

    function drawMap() {
        var data = google.visualization.arrayToDataTable([
            ['Country', 'Visitors'],
            <?php
                echo Mage::registry('country_data_map');
            ?>
        ]);
        var options = {
            showTooltip: true,
            showInfoWindow: true
        };
        var map = new google.visualization.Map(document.getElementById('chart_div'));
        map.draw(data, options);
    };
</script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>

<div class="dashboard-container" style="border:1px solid #ccc; width:550px;height:550px;padding:5px">
    <canvas id="myСountry" width="400" height="400"></canvas>
    <script>
        var my_chart_canvas = document.getElementById("myСountry");
        var my_chart = new Chart(my_chart_canvas, {
            type: 'doughnut',
            data: {
                datasets: [
                    {
                        data: [<?php echo Mage::registry('country_data');?>],
                        backgroundColor: [<?php echo Mage::registry('country_rgba');?>]
                    }
                ],
                labels: [<?php echo Mage::registry('country_legend');?>]
            },
            options: {
                layout: {
                    padding: {
                        left: 10,
                        right: 10,
                        top: 10,
                        bottom: 10
                    }
                },
                legend: {
                    display: true,

                },
                title: {
                    display: true,
                    text: '% стран посетителей',
                    fontSize: 15,
                }
            }
        });
    </script>
</div>

    <div class="dashboard-container" style="border:1px solid #ccc; width:700px;padding:5px">
        <canvas id="myYear"></canvas>
        <form class="my_year_bar_form_class" name="my_year_bar_form_name" id="my_year_bar_form_id" method="post" >
            <select multiple name="my_year[]">
                <?php for ($i = 2016; $i <= 2027; $i++):?>
                        <option value = "<?php echo $i?>"><?php echo $i?></option>
                <?php endfor;?>
            </select>
            <p>*-выбирайте с нажатым ctrl</p>
            <button id="year_bar_show">Show</button>
            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_bar_key"/>
        </form>
        <script>
            var my_chart_canvas = document.getElementById("myYear");
            var my_chart = new Chart(my_chart_canvas, {
                type: 'bar',
                data: {
                    labels: [<?php echo Mage::registry('month_legend');?>],
                    datasets: [<?php
                        foreach (Mage::registry('data_year_gist') as $value) {
                            echo $value;
                        }?>]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero:true,
                                userCallback: function(label, index) {
                                    if (Math.floor(label) === label) {
                                        return label;
                                    }
                                }
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Visits'
                            }
                        }],
                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'Month'
                            }
                        }]
                    }
                }
            });
        </script>
    </div>



<div class="dashboard-container" style="border:1px solid #ccc; width:700px;padding:5px">
    <canvas id="myMonth"></canvas>

    <form class="my_month_line_form_class" name="my_month_line_form_name" id="my_month_line_form_id" method="post" >
        <select multiple name="my_month[]">
            <?php foreach (Mage::registry('month_label') as $key=>$value):?>
                <option value = "<?php echo $key?>"><?php echo $value?></option>
            <?php endforeach;?>
        </select>
        <p>*-выбирайте с нажатым ctrl</p>
        <button id="month_line_show">Show</button>
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_month_line_key"/>

    </form>

    <script>
        var my_chart_canvas = document.getElementById("myMonth");
        var my_chart = new Chart(my_chart_canvas, {
            type: 'line',
            data: {
                labels: [<?php echo Mage::registry('day_legend');?>],
                datasets: [<?php foreach (Mage::registry('day_data') as $value){echo $value;}?>]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true,
                            userCallback: function(label, index) {
                                if (Math.floor(label) === label) {
                                    return label;
                                }
                            }
                        },
                        scaleLabel: {
                            display: true,
                            labelString: 'Visits'
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Day'
                        }
                    }]
                }
            }
        });
    </script>
</div>